### ISSUE TITLE
non-latin1 characters when importing from CrossRef

### ISSUE THREAD

**Issue by dahtah** [cpitclaudel/biblio.el#19]
Thanks for the great package. I've noticed a problem when importing BibTex references from CrossRef, namely that page range (e.g. 467-499) is encoded with an em-dash character rather than just a dash, which depending on the encoding causes pdflatex to complain. Would it be possible to replace the em-dash with a dash?

**Comment by cpitclaudel** [comment]
I can think of a few options:

One easy solution could be to add `\DeclareUnicodeCharacter{2013}{--}` to your preamble (or move to xelatex or lualatex, since they have great unicode support).

Another solution would be to request this feature in Emacs itself, as `bibtex-clean-entry` already supports a `page-dashes` option that converts `--` to `-`.

For just en dashes, you could use advice to add this on your side:

```elisp
(defun ~/remove-en-dashes (str)
  (replace-regexp-in-string "–" "--" str t t))

(with-eval-after-load 'biblio-core
  (advice-add #'biblio-format-bibtex :filter-return #'~/remove-en-dashes))
```

If the problem is more general, I can look into integrating the stuff I did for esh (https://github.com/cpitclaudel/esh/blob/master/esh-latex-escape.el) into this package.

**Comment by dahtah** [comment]
Thanks Clément, that's quite helpful. Solution (1) works, of course. For 
others who might run into the problem, though, maybe it's worth calling 
bibtex-clean-entry before exporting from CrossRef?

**Comment by cpitclaudel** [comment]
> maybe it's worth calling
> bibtex-clean-entry before exporting from CrossRef?

I think this is already done, actually. Am I misunderstanding?

**Comment by dahtah** [comment]
No, I'm the one who misunderstood. Thanks, marking this as fixed (but maybe worth documenting somewhere?)
