### ISSUE TITLE
Add hook after entry is inserted

### ISSUE THREAD

**Issue by jagrg** [cpitclaudel/biblio.el#5]
I would like to format the entry once it's inserted. In my case, I would like to use this command: https://github.com/jagrg/.emacs.d/blob/master/lisp/config-bibtex.el#L39, which generates a reference key and does a few other things to the entry.

**Comment by tmalsburg** [comment]
bibtex.el already has tools for cleaning up bibtex entries and biblio.el is already using that.  I think you only have to configure bibtex.el to suite your preferences with regards to key format etc.  See `bibtex-clean-entry` and the function `biblio--cleanup-bibtex`.

**Comment by jagrg** [comment]
Thanks for pointing these out. I'm aware of `bibtex-clean-entry`, but last time I checked I wasn't able to replace non-ascii characters. `biblio--cleanup-bibtex` has a good default, but it's not tailored to my needs. For example it uses `:` as the `bibtex-autokey-year-title-separator`. What if people want to use something else instead?

**Comment by tmalsburg** [comment]
Not an expert for bibtex-clean-entry but I think you can configure it to reformat the key as well.

Regarding non-ascii characters, what's the problem with just keeping them?  They don't cause any problems in my LaTeX documents.  The only place where they don't work is in keys.

**Comment by jagrg** [comment]
> Not an expert for bibtex-clean-entry but I think you can configure it to reformat the key as well.

How exactly are you doing this? I am only able to get `bibtex-clean-entry` to format the key correctly if I delete the old key first.

> Regarding non-ascii characters, what's the problem with just keeping them? They don't cause any problems in my LaTeX documents. The only place where they don't work is in keys.

Bibtex doesn't handle non-ascii characters too well. I know you use biblatex, so it doesn't apply to you. In any case, what do you do when you copy an entry from google scholar, like [this one]( https://scholar.google.com/scholar.bib?q=info:wXqm8ikdMhwJ:scholar.google.com/&output=citation&scisig=AAGBfm0AAAAAVwQTNV1QsSmg2CUFY0ODcWi9aQ09QHSl&scisf=4&hl=en)?

**Comment by tmalsburg** [comment]
> How exactly are you doing this? 

It's in the documentation: http://www.jonathanleroux.org/bibtex-mode.html#0630 Basically,  call `bibtex-clean-entry` with a prefix argument, e.g. `C-u C-c C-c`.

>  I know you use biblatex,

Do yourself a favor and switch to biblatex and biber.  They are a lot better.  I never looked back.

> what do you do when you copy an entry from google scholar, like this one?

The link doesn't work for me, but the answer is: I don't use BibTeX from Google Scholar because it's almost always crap.  I usually get BibTeX entries from the journal pages.

**Comment by cpitclaudel** [comment]
Neat discussion :)
I think biblio currently ignores part of your preferences for bibtex formatting, mostly because it's tricky to tell whether someone is using the (arguably not ideal) defaults, or whther they actually customized things. I think adding a `biblio-format-bibtex-function` defcustom would make sense.

**Comment by cpitclaudel** [comment]
@jagrg Would you think of this work?

```elisp
(defcustom biblio-cleanup-bibtex-function
  #'biblio--cleanup-bibtex
  "Function to clean up BibTeX entries.
This function is called in a `bibtex-mode' buffer containing an
unprocessed, potentially invalid BibTeX (or BibLaTeX) entry, and
clean it up in place.  The function is called with a single
argument, AUTOKEY, indicating whether the entry additionally
needs a new key."
  :group 'biblio
  :type 'function)
```

**Comment by tmalsburg** [comment]
Given the incredible flexibility of `bibtex-clean-entry`, I don't understand why we need the possibility to define a custom function, but I suppose it can't hurt either.

**Comment by jagrg** [comment]
@tmalsburg You are right, all we would need then is to add the argument `(bibtex-clean-entry t)`. In any case, it seems like biblio overrides my configuration. Maybe @cpitclaudel can help, but I'm getting: `Author_2000` in place of: `Author2000a`.

The reason I mentioned google scholar was that (I would assume) someone who uses google scholar and biblatex may need to convert the string back to ascii characters. BTW thanks again for pointing biblatex and biber.

@cpitclaudel I think adding a defcustom would work, yes.

**Comment by tmalsburg** [comment]
@jarg, for some reason biblio doesn't use `bibtex-entry-format` but `biblio-bibtex-entry-format`, so you have to use that latter variable.

> someone who uses google scholar and biblatex may need to convert the string back to ascii characters.

Could you paste the BibTeX from Scholar?  I could not open your link.

**Comment by jagrg** [comment]
@tmalsburg I gave your suggestion a try, but it still won't insert the right key. The autokey argument is nil for me.

`(bibtex-clean-entry autokey)`

RE google scholar, I was just wondering what you would do to revert the string back to ascii characters.

```
@article{damatta1979voce,
  title={Voc{\^e} sabe com quem est{\'a} falando?},
  author={DaMATTA, Roberto},
  journal={Carnavais, malandros e her{\'o}is},
  volume={3},
  year={1979},
  publisher={Zahar Eds Rio de Janeiro}
}
```

**Comment by tmalsburg** [comment]
Well, I don't know how to make it work with biblio.el; I'm a newbie myself.  But I think if biblio would just honor the settings for bibtex.el including for the key format that should make everyone happy.  I think there is also no need to use `biblio-bibtex-entry-format` because virtually everyone will want to use one consistent format.  So this probably causes more confusion than it helps.

> RE google scholar, 

Ah, when you said non-ascii, I was thinking UTF8.  I don't know how to convert the escaped characters.  I never had this problem because journals typically use utf8 (I believe).  Another possibility is to download RIS instead of BibTeX and to convert it to BibTeX using the following function:

``` elisp
(defun ris2bibtex ()
  (interactive)
  (shell-command-on-region (point-min) (point-max) "ris2xml | xml2bib -b -w" (current-buffer) t "*ris2bib*")
  (delete-blank-lines))

```

**Comment by cpitclaudel** [comment]
> Well, I don't know how to make it work with biblio.el; I'm a newbie myself. But I think if biblio would just honor the settings for bibtex.el including for the key format that should make everyone happy. I think there is also no need to use biblio-bibtex-entry-format because virtually everyone will want to use one consistent format. So this probably causes more confusion than it helps.

Here's the catch: ideally, biblio should insert ok-looking entries. However, `BibTeX-mode`'s default settings for cleaning entries don't do much at all; thus, to clean an entry up, I need to temporarily set some BibTeX settings.

In general, this will work well: it'll produce cleaner entries, without bothering users too much. On the other hands, it really isn't the best for power-users who already customized their `bibtex-mode` settings. (As I'm sure you know,) This is a problem that you constantly run in Emacs; there's no good way to say: "use the user's customizations, or **this** default if the user didn't customize this setting yet"

There's another issue; sources of BibTeX entries use different formats, and I don't want biblio to try to be too smart in manipulating these entries. That's why it tries BibTeX and biblatex; it's just trying hard to get bibtex-mode to reflow an entry; no more. I need the biblatex dialect to reformat @Online entries, and the BibTeX one for @TechReport entries, for example.

Then again, I recognize the need for respecting expert settings (of course :) That's why I think introducing a defcustom seems like the best option to me atm. The default should be a good no-effort solution, and one can just set the defcustom to get a different behaviour.

**Comment by tmalsburg** [comment]
Ok, I understand your reasoning now, and I agree that it's a tricky problem.  As you say there are two kinds of users: 1. users who want sensible defaults, 2. users who have tweaked their bibtex.el settings.  Perhaps, it makes sense to add a sentence to the docstring of `biblio-cleanup-bibtex-function` that explains how type-2 users can get their bibtex.el behavior.  Do they have to do

``` elisp
(setq biblio-cleanup-bibtex-function #'bibtex-clean-entry)
```

or is there more to it?

**Comment by jagrg** [comment]
Using my own function, I had to add an optional underscore argument. Otherwise I was getting an error.

`(defun bibtex-cleanup-entry (&optional _)`

I think setting `biblio-cleanup-bibtex-function` to `bibtex-clean-entry` alone will not update the key. We either have to add a defcustom to the autokey argument or the user will need to write his own function.

```
(defun my/bibtex-clean-entry ()
  (interactive)
  (bibtex-clean-entry t))
```
