### ISSUE TITLE
Avoid switching to biblatex automatically

### ISSUE THREAD

**Issue by jagrg** [cpitclaudel/biblio.el#6]
I noticed that when I insert a new entry from `biblio-lookup`, the dialect automatically changes to biblatex. If I run `bibtex-clean-entry`, bibtex.el complains that I'm missing the journaltitle.

**Comment by tmalsburg** [comment]
See the option `required-fields` in the documentation of `bibtex-entry-format`.

**Comment by jagrg** [comment]
Are you saying I should remove `required-fields`? I think I would rather fix the cause instead.

**Comment by tmalsburg** [comment]
If I understand correctly, biblio first tries biblatex style and when that throws en error it tries bibtex style.  At least that's what I see in the code of `biblio-format-bibtex`, but perhaps it doesn't work as intended.

I guess I agree with you, the style should be configurable by the user.

**Comment by cpitclaudel** [comment]
@jagrg Thanks for the report; this should be fixed

@tmalsburg I think the problem was that I was calling bibtex-set-dialect without giving it the `local` argument, so it was setting the dialect globally, instead of setting it just locally to the temporary buffer that is used for formatting entries.
